-- Initialize FinancialRuleEngine database tables

CREATE TABLE IF NOT EXISTS public."FinancialStatement" (
    "Id" int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "IdentityNumber" varchar(100) NOT NULL,
    "Period" int4 NOT NULL,
    "Code" varchar(100) NOT NULL,
    "OriginalValue" numeric(22, 2) NOT NULL,
    "CorrectedValue" numeric(22, 2) NOT NULL,
    CONSTRAINT "FinancialStatement_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT chk_financialstatement_period_length CHECK ((char_length(("Period")::text) = 6))
);

CREATE TABLE IF NOT EXISTS public."FinancialStatementItemDefinition" (
    "Id" int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "Code" varchar(100) NOT NULL,
    "Name" varchar(500) NOT NULL,
    "ParentCode" varchar(100) NULL,
    "SequenceNumber" int4 NOT NULL DEFAULT 0,
    "Sign" int4 NOT NULL DEFAULT 1,
    "IsLeaf" int4 NOT NULL DEFAULT 0,
    "BalanceSheet" int4 NOT NULL DEFAULT 0,
    "Description" varchar(2000) NULL,
    "Description2" varchar(2000) NULL,
    "Description3" varchar(2000) NULL,
    "Status" int4 NOT NULL DEFAULT 1,
    CONSTRAINT "FinancialStatementItemDefinition_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."FinancialStatementDetail" (
    "Id" int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "IdentityNumber" varchar(100) NOT NULL,
    "Period" int4 NOT NULL,
    "Code" varchar(100) NOT NULL,
    "Description" varchar(2000) NULL,
    "ParentCode" varchar(100) NULL,
    "Debit" numeric(22, 2) NOT NULL,
    "Credit" numeric(22, 2) NOT NULL,
    "DebitBalance" numeric(22, 2) NULL,
    "CreditBalance" numeric(22, 2) NULL,
    CONSTRAINT "FinancialStatementDetail_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT chk_financialstatementdetail_credit_positive CHECK (("Credit" >= (0)::numeric)),
    CONSTRAINT chk_financialstatementdetail_debit_positive CHECK (("Debit" >= (0)::numeric)),
    CONSTRAINT chk_financialstatementdetail_period_length CHECK ((char_length(("Period")::text) = 6))
);
