name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "dckr_pat_609krlE7r267TkUKqfTeyJL8sbI" | docker login -u "tarzan123" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tarzan123/mizanapp:latest

    - name: Push the Docker image
      run: docker push tarzan123/mizanapp:latest

    - name: Wait and trigger deploy
      run: |
        sleep 10
        curl -X GET http://176.96.131.184:3000/api/deploy/q7PsB218KBBhLsOakozWx
